@startuml lambda_relations

frame flexibleReversi_Lambdas {
    agent Connect
    agent Disconnect
    agent Default
    agent NewToken
    agent GetRooms
    agent UpdateRoom
    agent CheckEntryPassword
    agent flexibleReversiGameStandby

    UpdateRoom --> GetRooms
}

@enduml
