@startuml lambda_relations

frame flexibleReversi_Lambdas {
    agent Connect
    agent Disconnect
    agent Default
    agent newToken
    agent getRooms
    agent updateRoom
    agent checkEntryPassword
    agent gameStandby
    agent checkNicknameAvailability
    agent putStone

    updateRoom --> getRooms
}

frame flexibleReversi_DevUtil {
    agent devToolFlexibleReversiResetDBs
}

@enduml
