@startuml main_sequence

actor Player
participant Top
participant Nickname
participant RoomList
participant Game
participant ReversiBoard
participant ReversiCell
entity "Vuex store" as store
control newToken
control checkNicknameAvailability
database "flexible-reversi" as flexibleReversi
database "flexible-reversi-tokens" as tokens
database "flexible-reversi-nicknames" as nicknames

Player -> Top : 押下　スタート
activate Top
create Nickname
Top -> Nickname
deactivate Top
Nickname -> Nickname : created()
activate Nickname
alt this.currentPage !== "top"
    Nickname -> Top
end
Nickname -> Nickname : 呼出　InitializeWebSocket()
activate Nickname
deactivate Nickname
deactivate Nickname

group Nickname WebSocket接続確立
    Nickname -> newToken
    newToken -> newToken : トークン生成
    newToken -> tokens : 追加\n  トークン\n  エンドポイントURL\n  トークン有効期限\n  WebSocket 接続ID
    activate tokens
    tokens --> newToken : 追加完了
    deactivate tokens
    newToken -> Nickname : トークン
    Nickname -> store : 保存　トークン
    store --> Nickname : 保存完了
end

@enduml
